---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolutionweli/public_html/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolutionweli/ayw/
      - /bin/rsync -av ./ $DEPLOYPATH
