---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_aywsolution/
      - /bin/rsync -av ./ $DEPLOYPATH
